version: '3'
services:
    # Application container
    php:
        build: .
        restart: always
        container_name: pandora_cron_server
        volumes:
            - ../:/server/http
        ports:
            - "80:80"
        links:
            - mysql
        environment:
            DEBUG: 'true'
        command: php -S 0.0.0.0:80 -t public public/index.php

    mysql:
       image: mysql:5.7
       restart: always
       environment:
         MYSQL_DATABASE: 'db'
         MYSQL_USER: 'user'
         MYSQL_PASSWORD: 'password'
         MYSQL_ROOT_PASSWORD: 'password'
       ports:
         - '3306:3306'
       expose:
         - '3306'
       volumes:
         - my-db:/var/lib/mysql

volumes:
    my-db: